[workspace]
resolver = "2"
members = ["clients/rust", "program"]

[workspace.metadata.cli]
solana = "2.2.17"

# Specify Rust toolchains for rustfmt, clippy, and build.
# Any unprovided toolchains default to stable.
[workspace.metadata.toolchains]
format = "1.87.0"
lint = "1.87.0"
