max_width = 70
reorder_imports = true
reorder_modules = true

# == Nightly only. ==
# imports_indent = "Block"
# imports_layout = "Mixed"
# imports_granularity = "Crate"
# group_imports = "Preserve"
# reorder_impl_items = false
